version: '3'

volumes:
  pg_data_production:
  static:
  media:

services:
  kittygram_db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: khatkovskii/kittygram_backend
    env_file: .env
    depends_on:
      - kittygram_db
    volumes:
      - static:/static
      - media:/app/media
  frontend:
    env_file: .env
    image: khatkovskii/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: khatkovskii/kittygram_gateway
    env_file: .env
    depends_on:
      - backend
    volumes:
      - static:/static
      - media:/app/media
    ports:
      - 9000:80
