version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  kittygram_db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - kittygram_db
    volumes:
      - static:/static
      - media:/app/media

  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /static/
    depends_on:
      - backend
    volumes:
      - static:/static

  gateway:
    build: ./nginx/
    env_file: .env
    depends_on:
      - backend
    volumes:
      - static:/static
      - media:/app/media
    ports:
      - 9000:80
